### PR TITLE
Add CI and Linter for Backend

### PR DESCRIPTION
**Pull request by joshhn**
# Description

- Add black, pyright, pylint, isort, pre-commit hooks for backend and backend ci.
- Remove allauth

## Related PRs

n/a

### Please delete options that are not relevant

- [x] Styling change (non-breaking change which fixes a styling issue).
- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] This change requires a documentation update.

## Screenshots/Recordings

Screenshot 2024-10-25 at 13 33 08

## Testing instructions

`pre-commit` hooks will auto run whenever `git commit`

## Notes

n/a

### CODE REVIEW

**Comment by SamEGil00** [comment]
Is the pre-commit failed check gonna be an issue?

**Comment by ngoctramvu** [comment]
the linter is modifying frontend files as well, is it possible to only apply linter to backend folders

**Comment by joshhn** [comment]
> the linter is modifying frontend files as well, is it possible to only apply linter to backend folders

The pre-commit hook auto run whenever you `git commit`. It's not just for backend.

**Review by ngoctramvu — APPROVED** [review]
lgtm

**Pull request merged**
